apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oauth2-psp
rules:
- apiGroups:
  - policy
  resourceNames:
  - restricted
  resources:
  - podsecuritypolicies
  verbs:
  - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oauth2-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oauth2-psp
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts