apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: manifests
  namespace: flux-system
spec:
  interval: 60m
  url: https://github.com/axeal/manifests.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: manifests
  namespace: flux-system
spec:
  interval: 15m
  path: "./clusters/axe.al/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: manifests
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
